### ISSUE TITLE
Tokens without textures

### ISSUE THREAD

**Issue by najlitarvan** [SilentChaos512/Token-Enchanter#3]
## Versions

minecraft 1.16.5
forge 36.1.0
cofh_core-1.16.4-1.2.1
ensorcellation-1.16.4-1.2.0
FarmersDelight-1.16.3-0.4.0
silent-lib-1.16.3-4.9.6
token-enchanter-1.16.3-1.0.4

## Expected Behavior
All enchant tokens getting textures

## Actual Behavior
most of the enchants don't get a texture
the mods are farmer delight's backstabbing and ensorcelations enchants

## Links/Images
https://cdn.discordapp.com/attachments/474004489947316265/829783272770371644/unknown.png

- (log)
[latest.log](https://github.com/SilentChaos512/Token-Enchanter/files/6280917/latest.log)

## Steps to Reproduce the Problem

1. Install the said mods
2. open the creative menu
3. have a great surprise

**Comment by SilentChaos512** [comment]
OK, this will definitely require some code changes to make possible. I might also be able to build in support for those mods, but not sure at a glance.

(edit) Major code changes, actually... I forgot that the model properties have to be mapped to a number. Can't just put the name of the enchantment type into the model JSON. I'll have to think about how to best handle this.
