### ISSUE TITLE
[1.18.2] Failure to launch on Forge 40.0.54

### ISSUE THREAD

**Issue by Baggytrousers27** [SilentChaos512/Token-Enchanter#5]
- token-enchanter-1.18.2-1.3.0
- silent-lib-1.18.2-6.2.0
- Forge 40.0.54

[Debug log](https://pastebin.com/5zeKGXq8)

**Comment by SilentChaos512** [comment]
Seems to be a typo in the mods.toml file... I'll fix that when I get to my computer.
